src/apps/thirdparty/userena/urls.py
from django.conf.urls.defaults import *
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from userena import views as userena_views
from userena import settings as userena_settings

urlpatterns = patterns('',
    # Signup, signin and signout
    url(r'^signup/$',
       userena_views.signup,
       name='userena_signup'),
    url(r'^signin/$',
       userena_views.signin,
       name='userena_signin'),
    url(r'^signout/$',
       userena_views.signout,
       name='userena_signout'),

    # Reset password
    url(r'^password/reset/$',
       auth_views.password_reset,
       {'template_name': 'userena/password_reset_form.html',
        'email_template_name': 'userena/emails/password_reset_message.txt'},
       name='userena_password_reset'),
    url(r'^password/reset/done/$',
       auth_views.password_reset_done,
       {'template_name': 'userena/password_reset_done.html'},
       name='userena_password_reset_done'),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
       auth_views.password_reset_confirm,
       {'template_name': 'userena/password_reset_confirm_form.html'},
       name='userena_password_reset_confirm'),
    url(r'^password/reset/confirm/complete/$',
       auth_views.password_reset_complete,
       {'template_name': 'userena/password_reset_complete.html'}),

    # Signup
    url(r'^(?P<username>[\.\w]+)/signup/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/signup_complete.html',
        'extra_context': {'userena_activation_required': userena_settings.USERENA_ACTIVATION_REQUIRED,
                          'userena_activation_days': userena_settings.USERENA_ACTIVATION_DAYS}},
       name='userena_signup_complete'),

    # Activate
    url(r'^(?P<username>[\.\w]+)/activate/(?P<activation_key>\w+)/$',
       userena_views.activate,
       name='userena_activate'),

    # Change email and confirm it
    url(r'^(?P<username>[\.\w]+)/email/$',
       userena_views.email_change,
       name='userena_email_change'),
    url(r'^(?P<username>[\.\w]+)/email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_change_complete.html'},
       name='userena_email_change_complete'),
    url(r'^(?P<username>[\.\w]+)/confirm-email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_confirm_complete.html'},
       name='userena_email_confirm_complete'),
    url(r'^(?P<username>[\.\w]+)/confirm-email/(?P<confirmation_key>\w+)/$',
       userena_views.email_confirm,
       name='userena_email_confirm'),

    # Disabled account
    url(r'^(?P<username>[\.\w]+)/disabled/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/disabled.html'},
       name='userena_disabled'),

    # Change password
    url(r'^(?P<username>[\.\w]+)/password/$',
       userena_views.password_change,
       name='userena_password_change'),
    url(r'^(?P<username>[\.\w]+)/password/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/password_complete.html'},
       name='userena_password_change_complete'),

    # Edit profile
    url(r'^(?P<username>[\.\w]+)/edit/$',
       userena_views.profile_edit,
       name='userena_profile_edit'),

    # View profiles
    url(r'^(?P<username>(?!signout|signup|signin)[\.\w]+)/$',
       userena_views.profile_detail,
       name='userena_profile_detail'),
    url(r'^page/(?P<page>[0-9]+)/$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list_paginated'),
    url(r'^$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list'),
)

src/supervise.old/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
    supervise.urls
    ~~~~~~~~~~~~~~

    This file distributes all the URLs around Supervise apps.

    :copyright: (c) 2011 by Oscar Carballal Prego <oscarcp@clionesoftware.com>
    :license: Simplified BSD License, see LICENSE for more details.
"""

from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import settings

admin.autodiscover()

urlpatterns = patterns('',

    # Django administration interface
    url(r'^admin/', include(admin.site.urls)),

    # Uploads content #### FOR DEVELOPMENT!! ####
    url(r'^uploads/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_URL}),

    # User accounts
    url(r'^user/', include('supervise.apps.userprofile.urls'), name='user'),
    
    # Supervise index
    #url(r'^$', 'supervise.views.home'),
    
    # i18n language switcher
    url(r'^i18n/', include('django.conf.urls.i18n')),

    # Project index    
    #url(r'^(?P<project_name>[\w\-]+)/', include('supervise.apps.projects.urls'),
    #    name='projects'),
)

urlpatterns += staticfiles_urlpatterns()

src/supervise/urls.py
# -*- coding: utf-8 -*-
#
# Copyright (c) 2012 Clione Software
# Authors: Oscar Carballal Prego <oscar@clionesoftware.com>
# License: BSD Simplified (2-Clause BSD). See LICENSE for details.
#
# This file is part of Supervise project.

from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.utils.translation import ugettext_lazy as _

admin.autodiscover()

urlpatterns = patterns('',

    # url(r'^$', 'supervise.views.home', name='home'),

    # url(r'^supervise/', include('supervise.foo.urls')),

    url(r'^admin/', include(admin.site.urls)),

    # User accounts URLs
    url(r'^u/', include('apps.thirdparty.userena.urls')),

)

if settings.DEBUG:
    # Serve static files
    urlpatterns += staticfiles_urlpatterns()
    # Serve uploaded files
    urlpatterns += patterns('',
        url(r'^uploads/(?P<path>.*)$', 'django.views.static.serve',
                {'document_root': settings.MEDIA_ROOT}),
    )

src/supervise.old/apps/profiles/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
    supervise.apps.profiles.models
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    This file defines all the data models for extending the default django user
    profile.

    :copyright: (c) 2011 by Oscar Carballal Prego <oscarcp@clionesoftware.com>
    :license: Simplified BSD License, see LICENSE for more details.
"""
import datetime

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from supervise.apps.userprofile.models import BaseProfile

GENDER = (
    
    ('M', _('Male')),
    ('F', _('Female')),
    ('U', _('Unknown')),

)

class UserProfile(BaseProfile):
    firstname = models.CharField(_('Name'), max_length=50, blank=True)
    lastname = models.CharField(_('Last name'), max_length=200, blank=True)
    gender = models.CharField(_('Gender'), max_length=1, choices=GENDER,
                              blank=True)
    birthdate = models.DateField(_('Birth date'), blank=True, null=True)
    email = models.EmailField(_('Email'), unique=True)
    website = models.URLField(_('Website'), verify_exists=True, max_length=100,
                              null=True, blank=True,
                              help_text=_('The URL will be veryfied.'))
    
    def get_age(self):
        
        """
        Get current user age.
        """
        if self.birthdate is not None:
            diff = datetime.date.today() - self.birthdate
            years = diff.days/365
            return years
        else:
            return _('Unknown')
            
    def __unicode__(self):
        return self.firstname + self.lastname

src/supervise.old/apps/userprofile/models.py
# coding=UTF-8
from django.db import models
from django.contrib.sites.models import Site
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext as _
from django.template import loader, Context
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.conf import settings
from supervise.apps.userprofile.countries import CountryField
from django.core.files.storage import default_storage
if hasattr(settings, "AWS_SECRET_ACCESS_KEY"):
    try:
        from backends.S3Storage import S3Storage
        storage = S3Storage()
    except ImportError:
        raise S3BackendNotFound
else:
    storage = default_storage
import datetime
import cPickle as pickle
import base64
import urllib
import os.path
try:
    from PIL import Image, ImageFilter
except ImportError:
    import Image, ImageFilter

AVATAR_SIZES = getattr(settings, 'AVATAR_SIZES', (128, 96, 64, 48, 32, 24, 16))
DEFAULT_AVATAR_SIZE = getattr(settings, 'DEFAULT_AVATAR_SIZE', 96)
if DEFAULT_AVATAR_SIZE not in AVATAR_SIZES:
    DEFAULT_AVATAR_SIZE = AVATAR_SIZES[0]
MIN_AVATAR_SIZE = getattr(settings, 'MIN_AVATAR_SIZE', DEFAULT_AVATAR_SIZE)
DEFAULT_AVATAR = getattr(settings, 'DEFAULT_AVATAR', os.path.join(settings.STATIC_ROOT, "userprofile", "generic.jpg"))
DEFAULT_AVATAR_FOR_INACTIVES_USER = getattr(settings, 'DEFAULT_AVATAR_FOR_INACTIVES_USER', False)
# params to pass to the save method in PIL (dict with formats (JPEG, PNG, GIF...) as keys)
# see http://www.pythonware.com/library/pil/handbook/format-jpeg.htm and format-png.htm for options
SAVE_IMG_PARAMS = getattr(settings, 'SAVE_IMG_PARAMS', {})

class BaseProfile(models.Model):
    """
    User profile model
    """

    user = models.ForeignKey(User, unique=True)
    creation_date = models.DateTimeField(default=datetime.datetime.now)
    country = CountryField(null=True, blank=True)
    latitude = models.DecimalField(max_digits=10, decimal_places=6, blank=True, null=True)
    longitude = models.DecimalField(max_digits=10, decimal_places=6, blank=True, null=True)
    location = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        abstract = True

    def has_avatar(self):
        return Avatar.objects.filter(user=self.user, valid=True).count()

    def __unicode__(self):
        return _("%s's profile") % self.user

    def get_absolute_url(self):
        return reverse("profile_public", args=[self.user])


class Avatar(models.Model):
    """
    Avatar model
    """
    image = models.ImageField(upload_to="avatars/%Y/%b/%d", storage=storage)
    user = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True)
    valid = models.BooleanField()

    class Meta:
        unique_together = (('user', 'valid'),)

    def __unicode__(self):
        return _("%s's Avatar") % self.user

    def delete(self):
        if hasattr(settings, "AWS_SECRET_ACCESS_KEY"):
            path = urllib.unquote(self.image.name)
        else:
            path = self.image.path

        base, filename = os.path.split(path)
        name, extension = os.path.splitext(filename)
        for key in AVATAR_SIZES:
            try:
                storage.delete(os.path.join(base, "%s.%s%s" % (name, key, extension)))
            except:
                pass

        super(Avatar, self).delete()

    def save(self, *args, **kwargs):
        for avatar in Avatar.objects.filter(user=self.user, valid=self.valid).exclude(id=self.id):
            if hasattr(settings, "AWS_SECRET_ACCESS_KEY"):
                path = urllib.unquote(self.image.name)
            else:
                path = avatar.image.path

            base, filename = os.path.split(path)
            name, extension = os.path.splitext(filename)
            for key in AVATAR_SIZES:
                try:
                    storage.delete(os.path.join(base, "%s.%s%s" % (name, key, extension)))
                except:
                    pass
            avatar.delete()

        super(Avatar, self).save(*args, **kwargs)


class EmailValidationManager(models.Manager):
    """
    Email validation manager
    """
    def verify(self, key):
        try:
            verify = self.get(key=key)
            if not verify.is_expired():
                verify.user.email = verify.email
                if hasattr(settings, "REQUIRE_EMAIL_CONFIRMATION") and settings.REQUIRE_EMAIL_CONFIRMATION:
                    verify.user.is_active = True
                verify.user.save()
                verify.verified = True
                verify.save()
                return True
            else:
                if not verify.verified:
                    verify.delete()
                return False
        except:
            return False

    def getuser(self, key):
        try:
            return self.get(key=key).user
        except:
            return False

    def add(self, user, email):
        """
        Add a new validation process entry
        """
        while True:
            key = User.objects.make_random_password(70)
            try:
                EmailValidation.objects.get(key=key)
            except EmailValidation.DoesNotExist:
                break

        template_body = "userprofile/email/validation.txt"
        template_subject = "userprofile/email/validation_subject.txt"
        site_name, domain = Site.objects.get_current().name, Site.objects.get_current().domain
        body = loader.get_template(template_body).render(Context(locals()))
        subject = loader.get_template(template_subject).render(Context(locals())).strip()
        send_mail(subject=subject, message=body, from_email=None, recipient_list=[email])
        user = User.objects.get(username=str(user))
        self.filter(user=user).delete()
        return self.create(user=user, key=key, email=email)

class EmailValidation(models.Model):
    """
    Email Validation model
    """
    user = models.ForeignKey(User, unique=True)
    email = models.EmailField(blank=True)
    key = models.CharField(max_length=70, unique=True, db_index=True)
    verified = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    objects = EmailValidationManager()

    def __unicode__(self):
        return _("Email validation process for %(user)s") % { 'user': self.user }

    def is_expired(self):
        if hasattr(settings, 'EMAIL_CONFIRMATION_DELAY'):
            expiration_delay = settings.EMAIL_CONFIRMATION_DELAY
        else:
            expiration_delay = 1
        return self.verified or \
            (self.created + datetime.timedelta(days=expiration_delay) <= datetime.datetime.now())

    def resend(self):
        """
        Resend validation email
        """
        template_body = "userprofile/email/validation.txt"
        template_subject = "userprofile/email/validation_subject.txt"
        site_name, domain = Site.objects.get_current().name, Site.objects.get_current().domain
        key = self.key
        body = loader.get_template(template_body).render(Context(locals()))
        subject = loader.get_template(template_subject).render(Context(locals())).strip()
        send_mail(subject=subject, message=body, from_email=None, recipient_list=[self.email])
        self.created = datetime.datetime.now()
        self.save()
        return True

class UserProfileMediaNotFound(Exception):
    pass

class S3BackendNotFound(Exception):
    pass

class GoogleDataAPINotFound(Exception):
    pass

src/supervise.old/apps/userprofile/templates/userprofile/profile/delete.html
{% extends "userprofile/base_2col.html" %}
{% load i18n %}

{% block title %}{% trans "Delete personal information" %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block userprofile_navigation %}
{% include "userprofile/menu.html" %}
{% endblock %}

{% block userprofile_content %}
	<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
		<fieldset>
			<legend>{% trans "Delete your personal information" %}</legend>
			<p><label for="remove">{% trans "Are you sure?" %}</label> <input id="remove" type="submit" value="{% trans "Yes" %}" /></p>
		</fieldset>
	</form>
{% endblock %}

{% block userprofile_content_related %}
	<div class="box">
		<h3>{% trans "Remove profile" %}</h3>
		<p>{% trans "It erases all your private data except your username. You can refill the information later if you want to" %}.</p>
	</div>
{% endblock %}

src/supervise.old/apps/userprofile/templates/userprofile/profile/location.html
{% extends "userprofile/base_2col.html" %}
{% load i18n %}

{% block title %}{% blocktrans %}{{ user }}'s Dashboard{% endblocktrans %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block extrajs %}
	{% if GOOGLE_MAPS_API_KEY %}
	<script type="text/javascript" src="{{ MEDIA_URL }}userprofile/js/jquery.location.js"></script>
	{% endif %}
{% endblock %}

{% block userprofile_navigation %}
{% include "userprofile/menu.html" %}
{% endblock %}

{% block userprofile_content %}
	<form action="{% url profile_edit_location %}" method="post" enctype="multipart/form-data">{% csrf_token %}
	{{ form.errors }}
	<fieldset>
		<legend>{% trans "Define your location" %}{% if geoip %} (<a href="?ip=1">{% trans "Auto-discover location" %}</a>){% endif %}</legend>
		<label for="id_country">{% trans "Country" %}<img class="hide loading" alt="{% trans "Loading..." %}" src="{{ MEDIA_URL }}userprofile/images/loading.gif" /></label>
		<p>{{ form.country }}</p>
		{% if GOOGLE_MAPS_API_KEY %}
			<div class="mapinfo">
				<p><label>{% trans "Location:" %}</label> <span id="location_info">{{ form.instance.location }}</span></p>
				<label for="map">{% trans "Position" %}</label>
				<div id="map"></div>
			</div>
			<div class="hide">{{ form.location }}{{ form.latitude }}{{ form.longitude }}</div>
			<input type='hidden' name='_apikey' id="google_maps_apikey" value="{{ GOOGLE_MAPS_API_KEY }}" />
			<input type='hidden' name='_fetch_geodata_url' id="fetch_geodata_url" value="{% url profile_geocountry_info 0 0  %}" />
		{% endif %}
	</fieldset>
	<p><input type="submit" value="{% trans 'Save' %}" /></p>
	</form>
{% endblock %}
{% block userprofile_content_related %}
<div class="box">
  <h3>{% trans "Location information" %}</h3>
    <p>{% trans "Define your location information" %}.</p>
</div>
{% endblock %}

src/supervise.old/apps/userprofile/templates/userprofile/profile/overview.html
{% extends "userprofile/base_2col.html" %}
{% load i18n %}

{% block title %}{% trans "Overview of your profile" %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block extrajs %}
{% if GOOGLE_MAPS_API_KEY and user.get_profile.location %}
  <script src="http://maps.google.com/maps?file=api&amp;v=2.x&amp;key={{ GOOGLE_MAPS_API_KEY }}" type="text/javascript"></script>
  <script type="text/javascript">
    $(function() {
      if (GBrowserIsCompatible()) {
        this.map = new GMap2(document.getElementById("location"));
        this.map.disableDragging();
        this.map.setCenter(new GLatLng({{ user.get_profile.latitude|default:"30" }}, {{ user.get_profile.longitude|default:"0" }}), 2);
        this.marker = new GMarker(new GLatLng({{ user.get_profile.latitude }}, {{ user.get_profile.longitude }}), {clickable: false, draggable: false});
        this.map.addOverlay(this.marker);
      }
    });
  </script>
{% endif %}
{% endblock %}

{% block userprofile_navigation %}
{% include "userprofile/menu.html" %}
{% endblock %}

{% block userprofile_content %}
	{% load avatars %}
	<form action="" method="post">{% csrf_token %}
	<fieldset>
		<legend>{% trans "Overview of your profile" %}</legend>
		<div id="avatar" class="{{ css_classes.overview_avatar }} center">
			<a href="{% url profile_edit_avatar %}">
			</a>
			<p><a href="{% url profile_edit_avatar %}">{% if user.get_profile.has_avatar %}{% trans "Change avatar" %}{% else %}{% trans "Add avatar" %}{% endif %}</a></p>
		</div>
	
		<div class="{{ css_classes.overview_details }}">
			<p><label for="id_user">{% trans "Username:" %}</label> {{ user }}</p>
			<p><label for="id_email">{% trans "E-mail:" %}</label>
				<span class="{% if not email or not validated %}quiet red{% endif %}">
				{%if not email %}{% trans "Not set yet" %}
				{% else %}{{ email }}
				{% if not validated %}{% trans " (Not validated)" %}
				{% endif %}{% endif %}
				</span>
			</p>
			<p>
			<label for="location">{% trans "Country" %}:</label>
			{% if user.get_profile.country %}
				{{ user.get_profile.get_country_display }}
			{% else %}
				<span class="quiet red">{% trans "Not set" %}</span>
			{% endif %}
			</p>
			{% if GOOGLE_MAPS_API_KEY %}
			<p>
			<label for="location">{% trans "Location" %}:</label>
			{% if user.get_profile.location %}
				{{ user.get_profile.location }}
			{% else %}
				<span class="quiet red">{% trans "Not set" %}</span>
			{% endif %}
			</p>
			{% endif %}
			{% for field in fields %}
				<p><label for="id_{{ field.name }}">{{ field.verbose_name|title }}:</label>
			{% if field.value %}
				{{ field.value }}
			{% else %}
				<span class="quiet red">{% trans "Not set" %}</span>
			{% endif %}
			</p>
			{% endfor %}
		</div>

		<hr class="space" />
		{% if user.get_profile.location %}
		<div class="{{ css_classes.overview_location }}">
			<div id="location" style="width: 480px; height: 240px;"></div>
		</div>
		{% endif %}
	</fieldset>
	</form>
{% endblock %}

{% block userprofile_content_related %}
	<div class="box">
		<h3>{% trans "Management:" %}</h3>
		<a href="{% url password_change %}">{% trans "Change password" %}</a>
		<br />
		<a href="{% url email_validation %}">{% if email %}{% trans "Change your e-mail address" %}{% else %}{% trans "Add your e-mail address" %}{% endif %}</a>
		{% if not validated and email %}<br /><a href="{% url email_validation_reset %}">{% trans "Resend validation e-mail" %}</a>
		{% endif %}
		<br />
		{% if not user.get_profile.location %}
			<a href="{% url profile_edit_location %}">{% trans "Add location" %}</a>
		{% else %}
			<a href="{% url profile_edit_location %}">{% trans "Change location" %}</a>
		{% endif %}
	</div>
{% endblock %}

src/supervise.old/apps/userprofile/templates/userprofile/profile/personal.html
{% extends "userprofile/base_2col.html" %}
{% load i18n %}

{% block title %}{% trans "Edit your personal information" %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block extracss %}
	<link rel="stylesheet" href="{{ MEDIA_URL }}userprofile/css/ui.datepicker.css" type="text/css" />
{% endblock %}

{% block extrajs %}
<script type="text/javascript">
	$(function() {
		$("input[type='text']").addClass("text");
		$("form input")[0].focus();
	});
</script>
{% endblock %}

{% block userprofile_navigation %}
{% include "userprofile/menu.html" %}
{% endblock %}

{% block userprofile_content %}
	<form class="personal" action="{% url profile_edit_personal %}" method="post" enctype="multipart/form-data">{% csrf_token %}
	<fieldset>
		<legend>{% trans "Edit your personal information" %}</legend>
		{{ form.as_p }}
	</fieldset>
  <input type="submit" value="{% trans 'Save' %}" />
	</form>
{% endblock %}

{% block userprofile_content_related %}
  <div class="box">
    <h3>{% trans "Personal information" %}</h3>
    <p>{% trans "Insert some information about you" %}.</p>
  </div>
{% endblock %}

src/supervise.old/apps/userprofile/templates/userprofile/profile/public.html
{% extends "userprofile/base.html" %}
{% load i18n %}
{% load avatars %}

{% block title %}{{ profile.user }}'s public profile{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block extrajs %}
	{% if profile.latitude and profile.longitude %}
	<script type="text/javascript" src="http://www.google.com/jsapi?key={{ GOOGLE_MAPS_API_KEY }}"></script>
	<script type="text/javascript">google.load("maps", "2");</script>
	<script type="text/javascript">
		$(function() {
		if (google.maps.BrowserIsCompatible()) {
			var map = new google.maps.Map2(document.getElementById("map"));
      map.disableDragging();
			map.setCenter(new google.maps.LatLng({{ profile.latitude }}, {{ profile.longitude }}), 4);
			var marker = new google.maps.Marker(new google.maps.LatLng({{ profile.latitude }}, {{ profile.longitude }}), {clickable: false });
			map.addOverlay(marker);
		}
		});
	</script>
	{% endif %}
{% endblock %}

{% block userprofile_content %}
	<h2>{% blocktrans with profile.user as user %}Public profile of {{ user }}{% endblocktrans %}</h2>

	<div class="vcard">
		<div class="{{ css_classes.public_vcard_content }}">
			<img class="border top" alt="{{ profile.user }}" src="{% avatar DEFAULT_AVATAR_SIZE profile.user %}" />
			<ul>
				<li>{% trans "Username" %}: <strong>{{ profile.user }}</strong></li>
				{% if profile.country %}
				<li>{% trans "Country" %}: <strong>{{ profile.get_country_display }}</strong></li>
				{% endif %}
				{% if profile.location %}
				<li>{% trans "Location" %}: <strong>{{ profile.location }}</strong></li>
				{% endif %}
			</ul>
		</div>
		{% if profile.latitude and profile.longitude %}
		<div class="{{ css_classes.public_vcard_map }}">
			<div id="map"></div>
		</div>
		{% endif %}
	</div>
{% endblock %}