src/apps/thirdparty/userena/urls.py
from django.conf.urls.defaults import *
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from userena import views as userena_views
from userena import settings as userena_settings

urlpatterns = patterns('',
    # Signup, signin and signout
    url(r'^signup/$',
       userena_views.signup,
       name='userena_signup'),
    url(r'^signin/$',
       userena_views.signin,
       name='userena_signin'),
    url(r'^signout/$',
       userena_views.signout,
       name='userena_signout'),

    # Reset password
    url(r'^password/reset/$',
       auth_views.password_reset,
       {'template_name': 'userena/password_reset_form.html',
        'email_template_name': 'userena/emails/password_reset_message.txt'},
       name='userena_password_reset'),
    url(r'^password/reset/done/$',
       auth_views.password_reset_done,
       {'template_name': 'userena/password_reset_done.html'},
       name='userena_password_reset_done'),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
       auth_views.password_reset_confirm,
       {'template_name': 'userena/password_reset_confirm_form.html'},
       name='userena_password_reset_confirm'),
    url(r'^password/reset/confirm/complete/$',
       auth_views.password_reset_complete,
       {'template_name': 'userena/password_reset_complete.html'}),

    # Signup
    url(r'^(?P<username>[\.\w]+)/signup/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/signup_complete.html',
        'extra_context': {'userena_activation_required': userena_settings.USERENA_ACTIVATION_REQUIRED,
                          'userena_activation_days': userena_settings.USERENA_ACTIVATION_DAYS}},
       name='userena_signup_complete'),

    # Activate
    url(r'^(?P<username>[\.\w]+)/activate/(?P<activation_key>\w+)/$',
       userena_views.activate,
       name='userena_activate'),

    # Change email and confirm it
    url(r'^(?P<username>[\.\w]+)/email/$',
       userena_views.email_change,
       name='userena_email_change'),
    url(r'^(?P<username>[\.\w]+)/email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_change_complete.html'},
       name='userena_email_change_complete'),
    url(r'^(?P<username>[\.\w]+)/confirm-email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_confirm_complete.html'},
       name='userena_email_confirm_complete'),
    url(r'^(?P<username>[\.\w]+)/confirm-email/(?P<confirmation_key>\w+)/$',
       userena_views.email_confirm,
       name='userena_email_confirm'),

    # Disabled account
    url(r'^(?P<username>[\.\w]+)/disabled/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/disabled.html'},
       name='userena_disabled'),

    # Change password
    url(r'^(?P<username>[\.\w]+)/password/$',
       userena_views.password_change,
       name='userena_password_change'),
    url(r'^(?P<username>[\.\w]+)/password/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/password_complete.html'},
       name='userena_password_change_complete'),

    # Edit profile
    url(r'^(?P<username>[\.\w]+)/edit/$',
       userena_views.profile_edit,
       name='userena_profile_edit'),

    # View profiles
    url(r'^(?P<username>(?!signout|signup|signin)[\.\w]+)/$',
       userena_views.profile_detail,
       name='userena_profile_detail'),
    url(r'^page/(?P<page>[0-9]+)/$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list_paginated'),
    url(r'^$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list'),
)

src/supervise.old/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
    supervise.urls
    ~~~~~~~~~~~~~~

    This file distributes all the URLs around Supervise apps.

    :copyright: (c) 2011 by Oscar Carballal Prego <oscarcp@clionesoftware.com>
    :license: Simplified BSD License, see LICENSE for more details.
"""

from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import settings

admin.autodiscover()

urlpatterns = patterns('',

    # Django administration interface
    url(r'^admin/', include(admin.site.urls)),

    # Uploads content #### FOR DEVELOPMENT!! ####
    url(r'^uploads/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_URL}),

    # User accounts
    url(r'^user/', include('supervise.apps.userprofile.urls'), name='user'),
    
    # Supervise index
    #url(r'^$', 'supervise.views.home'),
    
    # i18n language switcher
    url(r'^i18n/', include('django.conf.urls.i18n')),

    # Project index    
    #url(r'^(?P<project_name>[\w\-]+)/', include('supervise.apps.projects.urls'),
    #    name='projects'),
)

urlpatterns += staticfiles_urlpatterns()

src/supervise/urls.py
# -*- coding: utf-8 -*-
#
# Copyright (c) 2012 Clione Software
# Authors: Oscar Carballal Prego <oscar@clionesoftware.com>
# License: BSD Simplified (2-Clause BSD). See LICENSE for details.
#
# This file is part of Supervise project.

from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.utils.translation import ugettext_lazy as _

admin.autodiscover()

urlpatterns = patterns('',

    # url(r'^$', 'supervise.views.home', name='home'),

    # url(r'^supervise/', include('supervise.foo.urls')),

    url(r'^admin/', include(admin.site.urls)),

    # User accounts URLs
    url(r'^u/', include('apps.thirdparty.userena.urls')),

)

if settings.DEBUG:
    # Serve static files
    urlpatterns += staticfiles_urlpatterns()
    # Serve uploaded files
    urlpatterns += patterns('',
        url(r'^uploads/(?P<path>.*)$', 'django.views.static.serve',
                {'document_root': settings.MEDIA_ROOT}),
    )

src/supervise.old/apps/userprofile/forms.py
from django import forms
from django.core.exceptions import ObjectDoesNotExist
from django.core.exceptions import ImproperlyConfigured
from django.db import models
from django.utils.translation import ugettext as _
from django.conf import settings
from django.contrib.auth.models import User, SiteProfileNotAvailable
from supervise.apps.userprofile.models import EmailValidation, AVATAR_SIZES, DEFAULT_AVATAR_SIZE, MIN_AVATAR_SIZE
from django.core.files.uploadedfile import SimpleUploadedFile
import mimetypes, urllib
from django.contrib.auth.forms import UserCreationForm

if not settings.AUTH_PROFILE_MODULE:
    raise SiteProfileNotAvailable
try:
    app_label, model_name = settings.AUTH_PROFILE_MODULE.split('.')
    Profile = models.get_model(app_label, model_name)
except (ImportError, ImproperlyConfigured):
    raise SiteProfileNotAvailable

class LocationForm(forms.ModelForm):
    """
    Profile location form
    """

    class Meta:
        model = Profile
        fields = ('location', 'latitude', 'longitude', 'country')

class ProfileForm(forms.ModelForm):
    """
    Profile Form. Composed by all the Profile model fields.
    """
    class Meta:
        model = Profile
        exclude = ('creation_date', 'location', 'latitude', 'longitude', 'country',
                   'user', 'public', 'site')

class PublicFieldsForm(forms.ModelForm):
    """
    Public Fields of the Profile Form. Composed by all the Profile model fields.
    """
    class Meta:
        model = Profile
        exclude = ('creation_date', 'user', 'public')

class AvatarForm(forms.Form):
    """
    The avatar form requires only one image field.
    """
    photo = forms.ImageField(required=False, help_text=_("Select an image from disk"))
    url = forms.URLField(required=False, help_text=_("Select an image from a remote URL. Put the URL on the input below and we'll retrieve the image for you"))

    def clean_url(self):
        url = self.cleaned_data.get('url')
        if not url: return ''
        try:
            filename, headers = urllib.urlretrieve(url)
        except:
            raise forms.ValidationError(forms.fields.URLField.default_error_messages['invalid_link'])
        if not mimetypes.guess_all_extensions(headers.get('Content-Type')):
            raise forms.ValidationError(_('The file type is invalid: %s' % type))
        return SimpleUploadedFile(filename, open(filename).read(), content_type=headers.get('Content-Type'))

    def clean(self):
        if not (self.cleaned_data.get('photo') or self.cleaned_data.get('url')):
            raise forms.ValidationError(_('You must enter one of the options'))
        return self.cleaned_data

class AvatarCoordinateField(forms.IntegerField):
    def clean(self, value):
        try:
            value = int(float(value))
        except:
            pass
        return super(AvatarCoordinateField, self).clean(value)

class AvatarCropForm(forms.Form):
    """
    Crop dimensions form
    """
    top = AvatarCoordinateField()
    bottom = AvatarCoordinateField()
    left = AvatarCoordinateField()
    right = AvatarCoordinateField()

    def __init__(self, image=None, *args, **kwargs):
        self.image = image
        super(AvatarCropForm, self).__init__(*args, **kwargs)

    def clean(self):
        if self.cleaned_data.get('right') and self.cleaned_data.get('left') and \
           int(self.cleaned_data.get('right')) - int(self.cleaned_data.get('left')) < MIN_AVATAR_SIZE:
            raise forms.ValidationError(_("You must select a portion of the image with a minimum of %(min_avatar_size)dx%(min_avatar_size)d pixels.") % { 'min_avatar_size': MIN_AVATAR_SIZE })

        return self.cleaned_data



class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=getattr(settings, "REQUIRE_EMAIL_CONFIRMATION", False), label=_("E-mail address"))

    class Meta:
        model = User
        fields = ("username","email",)

    def clean_email(self):
        """
        Verify that the email exists
        """
        email = self.cleaned_data.get("email")

        if not email: return  email

        try:
            User.objects.get(email__iexact=email)
            raise forms.ValidationError(_("That e-mail is already used."))
        except User.DoesNotExist:
            try:
                EmailValidation.objects.get(email=email)
                raise forms.ValidationError(_("That e-mail is already being confirmed."))
            except EmailValidation.DoesNotExist:
                return email

    def save(self, *args, **kwargs):
        user = super(RegistrationForm, self).save(commit=False)
        user.is_active = not getattr(settings, "REQUIRE_EMAIL_CONFIRMATION", False)
        user.save()
        if self.cleaned_data.get('email'):
            EmailValidation.objects.add(user=user, email=user.email)
        return user

try:
    _temp = settings.REGISTRATION_FORM.split('.')
    _form_class = _temp.pop()
    _module = __import__('.'.join(_temp), globals(), locals(), [_form_class])
    _RegistrationForm = getattr(_module, _form_class)
except:
    _RegistrationForm = RegistrationForm

class EmailValidationForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        """
        Verify that the email exists
        """
        email = self.cleaned_data.get("email")
        if not (User.objects.filter(email=email) or EmailValidation.objects.filter(email=email)):
            return email

        raise forms.ValidationError(_("That e-mail is already used."))

class ResendEmailValidationForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        """
        Verify that the email exists
        """
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email) or EmailValidation.objects.filter(email=email):
            return email

        raise forms.ValidationError(_("That e-mail isn't registered."))

src/supervise.old/apps/userprofile/templates/userprofile/avatar/choose.html
{% extends "userprofile/base_2col.html" %}
{% load i18n %}

{% block title %}{% trans "Choose the location of your avatar" %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block extrajs %}
<script type="text/javascript">
	$(function() {
	//avatar
		$("a.delavatar").click(function() {
			$.getJSON($(this).attr("href"), function(data) {
				if (data.success) {
					$("img#avatarimg").attr("src", "{{ generic }}");
					$("p#avatardelete").remove();
				}
			});
			return false;
		});

    $("div.photos a").click(function() {
      $("form input[name='url']").val($(this).attr("href"));
      $("form").submit();
      return false;
    });

	});
</script>
{% endblock %}

{% block userprofile_navigation %}
{% include "userprofile/menu.html" %}
{% endblock %}

{% block userprofile_content %}
	<form action="" method="post" accept-charset="utf-8" enctype="multipart/form-data">{% csrf_token %}
		<fieldset>
			<legend>{% trans "Choose the location of your avatar" %}</legend>
			<ul>
			<li>
				<label for="id_photo">{{ form.photo.help_text }}:</label>
				<p>{{ form.photo }}
				<input type="submit" value="{% trans 'Done' %}" />
				</p>
			</li>
			<li>
				<label for="id_url">{{ form.url.help_text  }}:</label>
				<p>{{ form.url }}
				<input type="submit" value="{% trans 'Done' %}" />
				</p>
			</li>
			{% if AVATAR_WEBSEARCH %}
  		<li>
    		<label for="id_search">{% trans "Search on Picasa Web" %}</label>
    		<p>
      		<input type="text" name="keyword" id="id_search" value="{{ keyword }}" />
      		<input type="submit" value="{% trans "Search" %}"/>
    		</p>

    		<div class="photos">
      		{% for thumb,url in images.items %}
      		<a href="{{ url }}"><img alt="photo{{ forloop.counter }}" src="{{ thumb }}" /></a>
      		{% endfor %}
    		</div>
			</li>
			{% endif %}
			</ul>
			{% if form.errors %}
			{% for error,desc in form.errors.items %}
			<p class="small quiet red">* {{desc|join:"; "}}</p>
			{% endfor %}
			{% endif %}
		</fieldset>
</form>
{% endblock %}

{% block userprofile_content_related %}
  <div class="box">
    <h3>{% trans "Avatar selection page" %}</h3>
		<p>{% trans "You have several options to select the image you want as avatar on your profile" %}.</p>
  </div>

	{% load avatars %}
  <div class="center">
		<img class="border" alt="{{ user }}" id="avatarimg" src="{% avatar DEFAULT_AVATAR_SIZE %}" />
    {% if user.get_profile.has_avatar %}<p id="avatardelete" style="text-align: center;"><a href="{% url profile_avatar_delete %}" class="delavatar">{% trans "Delete" %}</a></p>{% endif %}
	</div>
{% endblock %}

src/supervise.old/apps/userprofile/templates/userprofile/avatar/crop.html
{% extends "userprofile/base_2col.html" %}
{% load i18n %}

{% block title %}{% trans "Crop &amp; resize the area you want" %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block extrajs %}
<script type="text/javascript">DEFAULT_AVATAR_SIZE = {{ DEFAULT_AVATAR_SIZE }}; MIN_AVATAR_SIZE = {{ MIN_AVATAR_SIZE }};</script>
<script type="text/javascript" src="{{ MEDIA_URL }}userprofile/js/jquery.imgareaselect-0.8.min.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}userprofile/js/jquery.crop.js"></script>
{% endblock %}

{% block userprofile_navigation %}
{% include "userprofile/menu.html" %}
{% endblock %}

{% block userprofile_content %}
	<form name="cropavatar" action="{% url profile_avatar_crop %}" method="post" accept-charset="utf-8">{% csrf_token %}
	<fieldset>
		<legend style='display:none'>{% trans "Crop &amp; resize the area you want" %}</legend>

		{% if form.errors %}
			{% for error,desc in form.errors.items %}
				<p class="error">{{desc|join:"; "}}</p>
			{% endfor %}
		{% endif %}

		<div style="text-align: center;">
			<img src="{{ avatar.image.url }}" id="cropimage" />
		</div>
		<input type="hidden" name="top" value="0"/>
		<input type="hidden" name="bottom" value="0"/>
		<input type="hidden" name="left" value="0"/>
		<input type="hidden" name="right" value="0"/>
	</fieldset>
	<input type="submit" class="done" value="{% trans 'Done' %}" />
	</form>
{% endblock %}

{% block userprofile_content_related %}
  <div class="box">
    <h3>{% trans "Avatar selection page" %}</h3>
    <p>{% trans "You have several options to select the image you want as avatar on your profile" %}.</p>
  </div>

  {% load avatars %}
  <div class="center" id="avatarimg_container">
    <img class="border" id="avatarimg" src="{% avatar DEFAULT_AVATAR_SIZE %}" />
  </div>

{% endblock %}